food/urls.py
from importlib.resources import path
from unicodedata import name
from unittest.mock import patch
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.index, name='index'),
    path('item/', views.item, name='item'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('add', views.create_item, name='create_item')
]

food_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/", include("food.urls"))
]

food/models.py
from email.policy import default
from django.db import models

# Create your models here.


class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_description = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://assets.materialup.com/uploads/b03b23aa-aa69-4657-aa5e-fa5fef2c76e8/preview.png")

    def __str__(self):
        return self.item_name

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ['item_name', 'item_description', 'item_price', 'item_image']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
# Create your views here.


def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list
    }
    return render(request, 'food/index.html', context)
    # return HttpResponse(template.render(context, request))


def item(request):
    return HttpResponse('<h1> This is an item </h1>')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request, 'food/detail.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form})

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>FoodApp</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand abs" href="#">FoodApp</a>
            <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="collapseNavbar">
                {% comment %} <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="//codeply.com">Codeply</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#myAlert" data-bs-toggle="collapse">Link</a>
                    </li>
                </ul> {% endcomment %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Delete Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">View Item</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 pt-2">
                <img style="height:400px" class="card" src="{{ item.item_image }}" alt="food_image">
            </div>
            <div class="col-md-6 pt-2">
                <h1> {{ item.item_name }} </h1>
                <h2> {{ item.item_description }} </h2>
                <h3>${{ item.item_price }} </h3>
            </div>    
        </div>
    </div>
{% endblock %}   

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% block body %}

        {% for item in item_list %}
        {% comment %} <div class="row">
            <div class="col-md-3 pl-3" style="padding-left:50px">
                <img class="card" style="height:250px" src="{{ item.item_image }}" alt="image">
            </div>
            <div class="col-md-6 pl-3" style="padding-left:150px">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_description }}</h5>
                <h6>${{ item.item_price }}</h6>
            </div>
            <div class="col-md-3 pt-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

            </div>
        </div>  {% endcomment %}

            <div class="row">
                <div class="col-md-3 offset-md-2 pt-2">
                    <img class="card" style="height:250px" src="{{ item.item_image }}" alt="image">
                </div>
                <div class="col-md-5 pt-2" style="padding-left:150px">
                    <h3>{{ item.item_name }}</h3>
                    <h5>{{ item.item_description }}</h5>
                    <h6>${{ item.item_price }}</h6>
                </div>
                <div class="col-md-2 pt-2">
                    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

                </div>
            </div> 
        {% endfor %}

    {% endblock %}
    {% comment %} <ul>
        <li>
            <a href="{% url 'food:detail' item.id %}"> {{ item.id }} --> {{ item.item_name }} </a>
        </li>
    </ul> {% endcomment %}
</body>
</html>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>
{% endblock %} 